'use client';

import { usePathname } from 'next/navigation';
// import NavBar from '../../global-components/nav-bar';
import { Metadata } from 'next';
import TemplateComponent from '../../components/template-component';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function RealEstateTemplate({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  function renderImportantInfo() {
    // TODO: render each each component and handle dynamic transaction-ids
    switch (pathname) {
      case '/real-estate':
        return <div>Real Estate General</div>;
      case '/real-estate/new-property-info':
        return <div>New Property Info</div>;
      case '/real-estate/transaction-registration':
        return <div>New Transaction Registration</div>;
      case '/real-estate/add-change':
        return <div>Add/Change</div>;
      case '/real-estate/edm-document':
        return <div>EDM Document Upload</div>;
      case '/real-estate/instruction-to-pay-commission':
        return <div>Instruction to Pay Commission</div>;
      case '/real-estate/commission-disbursement':
        return <div>Commission Disbursement</div>;
    }
  }
  console.log('printing usePathname', pathname);
  return (
    <section>
      {/* <NavBar /> */}
      <TemplateComponent renderImportantInfo={renderImportantInfo}>{children}</TemplateComponent>
    </section>
  );
}
