import Image from 'next/image';
import { transactionsServices } from './api/transactions/transactions-services';
// import { Transactions } from '@/sanity/schema.types';
import { PortableText } from '@portabletext/react';
import TransactionComponent from './TransactionComponent';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'VirtualAgents360 Home Page',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return (
    <main className='flex min-h-screen flex-col items-center justify-between p-24'>
      this is a test
    </main>
  );
}
