// const inter = Inter({ subsets: ['latin'] });

import NavBar from '../global_components/Navbar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function RealEstateLayout({ children }: { children: React.ReactNode }) {
  return (
    <section>
      {/* <NavBar /> */}
      <div>{children}</div>
    </section>
  );
}
