// import { Transactions } from '@/sanity/schema.types';
import { Metadata } from 'next';
import CTASection from './components/cta-section';
import HeroSection from './components/hero-section';
import MortgageSection from './components/mortgage-section';
import RealEstateSection from './components/real-estate-section';
import SmartBuySection from './components/smart-buy-section';

export const metadata: Metadata = {
    title: 'VirtualAgents360 Home Page',
    description: 'Generated by create next app',
};

export default function HomePage() {
    return (
        <main className='w-full space-y-4'>
            <HeroSection />
            <SmartBuySection />
            <RealEstateSection />
            <MortgageSection />
            <CTASection />
        </main>
    );
}
