'use client';

import { usePathname } from 'next/navigation';
// import NavBar from '../../global-components/nav-bar';
import TransactionFormLayout from '@/app/(transactions)/shared-components/transaction-form-view';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
    title: 'Home Page',
    description: 'Generated by create next app',
};

export default function RealEstateTemplate({ children }: { children: React.ReactNode }) {
    const pathname = usePathname();

    // function renderImportantInfo() {
    //   // TODO: render each each component and handle dynamic transaction-ids
    //   console.log('printing pathname', pathname.split('/'));
    // }

    return (
        <section>
            {/* <NavBar /> */}
            <Suspense fallback={<p>Loading from real estate transaction template</p>}>
                <TransactionFormLayout type='real-estate'>{children}</TransactionFormLayout>
            </Suspense>
        </section>
    );
}
