'use client';

import { usePathname } from 'next/navigation';
// import NavBar from '../../global-components/nav-bar';
import TransactionFormView from '@/app/(transactions)/shared-components/transaction-form-view';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function RealEstateTemplate({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  // function renderImportantInfo() {
  //   // TODO: render each each component and handle dynamic transaction-ids
  //   console.log('printing pathname', pathname.split('/'));
  // }

  return (
    <section>
      {/* <NavBar /> */}
      <TransactionFormView type='real-estate'>{children}</TransactionFormView>
    </section>
  );
}
