import { transactionsServices } from '../api/transactions/transactions-services';
// import { Transactions } from '@/sanity/schema.types';
import { PortableText } from '@portabletext/react';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'VirtualAgents360 Home Page',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return (
    <main className='space-y-4'>
      <div className=''>this is a test</div>
      <div>
        <Link className='border-red-500 bg-red-500 p-2 rounded' href='/admin'>
          Admin Tools
        </Link>
      </div>
    </main>
  );
}
