// import { Transactions } from '@/sanity/schema.types';
import { Metadata } from 'next';
import Link from 'next/link';
import HeroSection from './components/hero-section';
import SmartBuySection from './components/smart-buy-section';

export const metadata: Metadata = {
    title: 'VirtualAgents360 Home Page',
    description: 'Generated by create next app',
};

export default function HomePage() {
    return (
        <main className='space-y-4'>
            <HeroSection />
            <SmartBuySection />
            <div>
                <Link className='rounded border-red-500 bg-red-500 p-2' href='/admin'>
                    Admin Tools
                </Link>
            </div>
        </main>
    );
}
