import { transactionsServices } from '../api/transactions/transactions-services';
// import { Transactions } from '@/sanity/schema.types';
import { PortableText } from '@portabletext/react';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'VirtualAgents360 Home Page',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return (
    <main className=''>
      this is a test
      <div>
        <Link href='/admin'>Go to admin</Link>
      </div>
    </main>
  );
}
